blank_issues_enabled: true
contact_links:
  - name: Long Questions or Ideas?
    url: https://github.com/next-friday/next-friday-turbo-repo/discussions
    about: Engage in detailed discussions, ask long-form questions, and share ideas.
  - name: Discord Community Chat
    url: https://discord.gg/next-friday-turbo-repo
    about: Connect with the `next-friday-turbo-repo` community on Discord for quick questions or casual chat.
  - name: Stay Updated (Twitter)
    url: https://twitter.com/next-friday-turbo-repo
    about: Follow our Twitter account to stay informed about the latest news and updates from next-friday-turbo-repo.
